services:
#    p6_user.example:
#        class: p6\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    p6\UserBundle\Controller\RegistrationController:
        autowire : true
        tags: [controller.service_arguments]

    p6\UserBundle\Controller\SecurityController:
      autowire : true
      tags: [controller.service_arguments]
