<?php

namespace p6\CoreBundle\Repository;

/**
 * vidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class vidRepository extends \Doctrine\ORM\EntityRepository
{
}
